### ISSUE TITLE
Droplet example manifest is outdated

### ISSUE THREAD

**Issue by raz-bn** [crossplane-contrib/provider-digitalocean#40]
### What happened?

When trying to follow the installing guild, trying to create the Droplet instance results an error. 

### How can we reproduce it?

`kubectl create -f examples/compute/droplet.yaml`

### What environment did it happen in?
Any environment

Crossplane version: 1.7.0

**Comment by ADustyOldMuffin** [comment]
Just of note, we don't currently support Crossplane version 1.7 and are currently on 1.6.4. Not sure if it's related or not.

**Comment by ADustyOldMuffin** [comment]
I didn't get an error though, I got an endless loop of making droplets.

**Comment by ADustyOldMuffin** [comment]
After some poking around, I'm thinking it might have something to do with this block of code.

https://github.com/crossplane-contrib/provider-digitalocean/blob/a84e31b85e4f7dccfbf964b8ade97e12e4dba6fe/pkg/controller/compute/droplet.go#L99-L110 

I noticed not a lot of the other providers make these comparisons and actually just write to the external name with the ID even if it has a value. I'm thinking we should move to do the same.

**Comment by hasheddan** [comment]
> we don't currently support Crossplane version 1.7

Just to clarify here, you should definitely be compatible with Crossplane v1.7.0, there are no breaking changes from v1.6.x to v1.7.x. The issue referenced was just do to some backdoor things the integration tests do, which we actually now have a fix for as well (I can open a PR to bump 👍🏻).

The issue here is likely the fact that the [`NewNameAsExternalName` initializer](https://github.com/crossplane/crossplane-runtime/blob/988c9ba9c255d7cade32e2c0135ce47b083eaf95/pkg/reconciler/managed/api.go#L51) is not being used, so your external name annotation is always empty in the code block you referenced. It can be added [here](https://github.com/crossplane-contrib/provider-digitalocean/blob/a84e31b85e4f7dccfbf964b8ade97e12e4dba6fe/pkg/controller/compute/droplet.go#L64). Here is [an example](https://github.com/crossplane/provider-aws/blob/ef937a609e3b94294a1fba58a44bd2d2b1a50011/pkg/controller/database/rdsinstance.go#L71) from `provider-aws`.

**Comment by hasheddan** [comment]
@ADustyOldMuffin here is a more concrete breakdown of what is happening. There are really two scenarios:
1. User sets `external-name` annotation. In this case, you'll [fail to parse to an ID](https://github.com/crossplane-contrib/provider-digitalocean/blob/a84e31b85e4f7dccfbf964b8ade97e12e4dba6fe/pkg/controller/compute/droplet.go#L104), causing the subsequent `GET` [to fail](https://github.com/crossplane-contrib/provider-digitalocean/blob/a84e31b85e4f7dccfbf964b8ade97e12e4dba6fe/pkg/controller/compute/droplet.go#L107), which will trigger creation. Creation will be successful, but since you already have the `external-name` set to a value that is not the external ID, it [won't get updated](https://github.com/crossplane-contrib/provider-digitalocean/blob/a84e31b85e4f7dccfbf964b8ade97e12e4dba6fe/pkg/controller/compute/droplet.go#L161). This means on the next reconcile you'll do the same song and dance and create a new Droplet... and so on and so on.
2. User has not set `external-name` annotation. In this case, you [abort early](https://github.com/crossplane-contrib/provider-digitalocean/blob/a84e31b85e4f7dccfbf964b8ade97e12e4dba6fe/pkg/controller/compute/droplet.go#L93) in your observation and trigger creation. In your create method, you [appear to be eventually setting](https://github.com/crossplane-contrib/provider-digitalocean/blob/a84e31b85e4f7dccfbf964b8ade97e12e4dba6fe/pkg/controller/compute/droplet.go#L162) the `external-name`, so I'm not sure if there is a bug taking place on that path or not. If there is, happy to dive in further on that with you 👍🏻

**Comment by richardjennings** [comment]
@ADustyOldMuffin @hasheddan Is any one working on resolving this ? I would like to pick it up if not.

**Comment by ADustyOldMuffin** [comment]
Hello @richardjennings there's an open PR but there hasn't been any movement so if you want to make another go for it!
